FROM golang:1.24-alpine AS build

WORKDIR /app

COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download

COPY ./cmd ./cmd/
RUN go build -o server ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/server .

EXPOSE 3000

CMD ["./server"]
